# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beatplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Polyrhythm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rhythm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhythm_name', models.CharField(max_length=20)),
                ('timing', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='polyrhythm',
            name='rhythm1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rhythm1', to='app.Rhythm'),
        ),
        migrations.AddField(
            model_name='polyrhythm',
            name='rhythm2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rhythm2', to='app.Rhythm'),
        ),
        migrations.AddField(
            model_name='beatplay',
            name='related_rhythm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beatplays', to='app.Rhythm'),
        ),
        migrations.AddField(
            model_name='beatplay',
            name='sounds',
            field=models.ManyToManyField(blank=True, related_name='m2m_sound_beatplay', to='app.Sound'),
        ),
    ]
